services:

  db:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - path: ../.env
        required: false
  
  # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
  # (Adding the "ports" property to this file will not forward from a Codespace.)

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
      #- ./init-minio.sh:/init-minio.sh
    command: minio server /data --console-address ":9001"
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

networks:
  default:
    driver: bridge

volumes:
  postgres-data:
  minio_data:
  redis-data: